USE [master]
GO

/****** Object:  Database [SearchEngine]    Script Date: 4/2/2018 6:58:10 PM ******/
CREATE DATABASE [SearchEngine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SearchEngine', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SearchEngine32.mdf' , SIZE = 27840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SearchEngine_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SearchEngine_log32.ldf' , SIZE = 94528KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SearchEngine] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SearchEngine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SearchEngine] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SearchEngine] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SearchEngine] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SearchEngine] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SearchEngine] SET ARITHABORT OFF 
GO

ALTER DATABASE [SearchEngine] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SearchEngine] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SearchEngine] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SearchEngine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SearchEngine] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SearchEngine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SearchEngine] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SearchEngine] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SearchEngine] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SearchEngine] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SearchEngine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SearchEngine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SearchEngine] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SearchEngine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SearchEngine] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SearchEngine] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SearchEngine] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SearchEngine] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SearchEngine] SET  MULTI_USER 
GO

ALTER DATABASE [SearchEngine] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SearchEngine] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SearchEngine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SearchEngine] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SearchEngine] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SearchEngine] SET  READ_WRITE 
GO

